# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifugio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('localita', models.CharField(max_length=800)),
                ('sezione', models.CharField(max_length=200)),
                ('regione', models.CharField(max_length=200)),
            ],
        ),
    ]
