# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('infomont_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifugio',
            name='categoria_cai',
            field=models.CharField(choices=[('E', 'Escursionistico'), ('A', 'Aplinistico')], default='E', max_length=1, verbose_name='Categoria CAI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifugio',
            name='data_aggiornamento',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 22, 20, 27, 49529, tzinfo=utc), verbose_name='Data Aggiornamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifugio',
            name='data_inserimento',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 22, 20, 36, 103358, tzinfo=utc), verbose_name='Data Inserimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rifugio',
            name='tipo_rifugio',
            field=models.CharField(choices=[('Custodito', 'Custodito'), ('Bivacco', 'Bivacco'), ('Stagionale', 'Stagionale')], default='Custodito', max_length=1, verbose_name='Tipo Rifugio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='localita',
            field=models.CharField(max_length=800, verbose_name='Località'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='regione',
            field=models.CharField(max_length=200, verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='sezione',
            field=models.CharField(max_length=200, verbose_name='Sezione'),
        ),
    ]
