# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infomont_app', '0002_auto_20170612_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Gruppo')),
            ],
        ),
        migrations.CreateModel(
            name='LayoutCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Pagina')),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infomont_app.Gruppo')),
            ],
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Paragrafo')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infomont_app.Pagina')),
            ],
        ),
        migrations.AddField(
            model_name='rifugio',
            name='commisione',
            field=models.CharField(default='---', max_length=200, verbose_name='Commissione Regionale'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='compentenza',
            field=models.CharField(default='---', max_length=200, verbose_name='Ente Sovracomunale di Competenza'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='comprensorio',
            field=models.CharField(default='---', max_length=200, verbose_name='Comprensorio Sciistico'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='comune',
            field=models.CharField(default='---', max_length=200, verbose_name='Comune'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='gruppo',
            field=models.CharField(default='---', max_length=200, verbose_name='Gruppo Montuoso'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='provincia',
            field=models.CharField(default='---', max_length=200, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='quota',
            field=models.IntegerField(default='0', verbose_name='Quota'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='sito',
            field=models.CharField(default='---', max_length=200, verbose_name='Sito Web'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='utm_wgs84',
            field=models.DecimalField(decimal_places=5, default='0', max_digits=5, verbose_name='UTM WGS84'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='valle',
            field=models.CharField(default='---', max_length=200, verbose_name='Valle'),
        ),
        migrations.AddField(
            model_name='rifugio',
            name='zona_tutelata',
            field=models.CharField(default='---', max_length=200, verbose_name='Zona Tutelata'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='categoria_cai',
            field=models.CharField(choices=[('E', 'Escursionistico'), ('A', 'Aplinistico')], default='E', max_length=1, verbose_name='Categoria CAI'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='localita',
            field=models.CharField(default='---', max_length=800, verbose_name='Località'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='nome',
            field=models.CharField(default='---', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='regione',
            field=models.CharField(default='---', max_length=200, verbose_name='Regione'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='sezione',
            field=models.CharField(default='---', max_length=200, verbose_name='Sezione'),
        ),
        migrations.AlterField(
            model_name='rifugio',
            name='tipo_rifugio',
            field=models.CharField(choices=[('Custodito', 'Custodito'), ('Bivacco', 'Bivacco'), ('Stagionale', 'Stagionale')], default='Bivacco', max_length=1, verbose_name='Tipo Rifugio'),
        ),
        migrations.AddField(
            model_name='layoutcampo',
            name='paragrafo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infomont_app.Paragrafo'),
        ),
    ]
