# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infomont_app', '0007_auto_20170613_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rifugio',
            old_name='commisione',
            new_name='commissione',
        ),
    ]
